DROP TABLE IF EXISTS m_users_departments;
DROP TABLE IF EXISTS t_announcements;

DROP TABLE IF EXISTS m_users;
DROP TABLE IF EXISTS m_departments;

DROP TABLE IF EXISTS m_position;
DROP TABLE IF EXISTS m_announcements_category;

CREATE TABLE m_users (
  user_id           VARCHAR(32)   PRIMARY KEY
,	password          VARCHAR(255)  NOT NULL
,	role              VARCHAR(15)   NOT NULL
,	family_name       VARCHAR(50)   NOT NULL
,	given_name        VARCHAR(50)   NOT NULL
,	family_name_kana  VARCHAR(50)   NOT NULL
,	given_name_kana   VARCHAR(50)   NOT NULL
,	mail              VARCHAR(255)  UNIQUE
,	position_cd       VARCHAR(3)
,	extension_tel     VARCHAR(50)
,	mobile_tel        VARCHAR(50)
,	birthday          DATE
, gender            VARCHAR(3)
,	hire_date         DATE
,	resignation_date  DATE
,	account_enabled   BOOLEAN       NOT NULL
,	add_date          DATETIME      NOT NULL
,	upd_date          DATETIME      NOT NULL
,	last_login_date 	DATETIME
);

CREATE TABLE m_departments (
  dept_cd           VARCHAR(3)    PRIMARY KEY
, dept_name         VARCHAR(50)   NOT NULL
, display_order     INT           UNIQUE
);

CREATE TABLE m_users_departments (
  dept_cd           VARCHAR(3)
, user_id           VARCHAR(32)
, is_main           BOOLEAN        NOT NULL 
, CONSTRAINT fk_users FOREIGN KEY(user_id) REFERENCES m_users(user_id) ON DELETE CASCADE
, CONSTRAINT fk_departments FOREIGN KEY(dept_cd)  REFERENCES m_departments(dept_cd) ON DELETE CASCADE
, PRIMARY KEY(dept_cd, user_id)
);

CREATE TABLE m_position (
  position_cd       VARCHAR(3)     PRIMARY KEY
, position_name     VARCHAR(50)    NOT NULL
, display_order     INT            UNIQUE
);

CREATE TABLE t_announcements(
  announcement_id   INT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY -- 自動採番＋主キー
, title             VARCHAR(100)   NOT NULL
, content           VARCHAR(500)   NOT NULL
, category_cd       VARCHAR(3)     NOT NULL    
, publish_date      DATETIME
, expires_date      DATETIME
, create_user_id    VARCHAR(30)
, add_date          DATETIME
, upd_date          DATETIME
-- 外部キー制約：m_usersに登録がないuser_idは禁止
, CONSTRAINT fk_announcement_user FOREIGN KEY (create_user_id) REFERENCES m_users (user_id) ON DELETE SET NULL
);

CREATE TABLE m_announcements_category(
	category_cd       VARCHAR(3)     PRIMARY KEY
, category_name     VARCHAR(50)    NOT NULL
, display_order     INT            UNIQUE
, color				VARCHAR(20)   
)